name: Build

on:
  - push

jobs:
  build:
    name: ${{ matrix.os }}
    matrix:
        os: [ubuntu-20.04, macos-11, windows-2019]
    runs-on: "build: ${{ matrix.os }}"
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        with:
          enable-stack: true
      - run: stack build
